version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "9090:9090"
    environment:
      DB_HOST: db
    container_name: telegram-bot
    depends_on:
      - db

  db:
    image: "postgres"
    ports:
      - "5433:5432"
    container_name: db
    environment:
      POSTGRES_DB: botdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres