telegram:
  bot:
    username: studB_bot
    token: 1890317072:AAEZgmuxsNZ3HelzXNgHxbXTpzJ0_c-KSys
    link:
      about-page: https://www.db.by/about/
      portfolio-page: https://www.db.by/portfolio/
      feedbacks-page: https://www.db.by/about/client-reviews/
      contacts-page: https://www.db.by/contact/

schedule:
  fixedDelayMs: 5000

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5433/botdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreplay.studBot@gmail.com
    password: Parol_bot1
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

email:
  recipient:
    address: umaxim2000@mail.ru

